/*
 * flOw Recomp — Entry point
 *
 * Initializes the ps3recomp runtime (memory subsystem, thread manager,
 * HLE module tables), creates the main PPU thread, and enters the
 * recompiled game entry point.
 */

#include "config.h"
#include "elf_loader.h"

#include <ps3emu/ps3types.h>
#include <ps3emu/error_codes.h>

#include <cstdio>
#include <cstdlib>
#include <cstring>

/* ---------------------------------------------------------------------------
 * Forward declarations for runtime subsystems (provided by ps3recomp)
 * -----------------------------------------------------------------------*/

/* Memory subsystem */
namespace ps3::memory {
    bool init(size_t main_ram_size);
    void shutdown();
}

/* Thread subsystem */
namespace ps3::thread {
    bool init(int max_threads);
    void shutdown();
    uint64_t create_main_thread(void (*entry)(uint64_t), uint64_t arg,
                                uint32_t stack_size, const char* name);
    void join_thread(uint64_t id);
}

/* Module / NID subsystem */
namespace ps3::modules {
    bool init();
    void shutdown();
    void register_builtin_modules();
    void override_nid(uint32_t nid, void* function_ptr);
}

/* Filesystem path mapping */
extern "C" {
    extern char g_sys_fs_root[512];
}

/* Recompiled function table -- generated by the recompiler tool */
struct RecompiledFunc {
    uint32_t    guest_addr;
    void      (*host_func)(void* ctx);
};

extern const RecompiledFunc g_recompiled_funcs[];
extern const size_t         g_recompiled_func_count;

/* The game's recompiled main function */
extern void recomp_game_main(void* ctx);

/* ---------------------------------------------------------------------------
 * Banner
 * -----------------------------------------------------------------------*/

static void print_banner(void)
{
    printf("================================================\n");
    printf("  flOw - Static Recompilation\n");
    printf("  Title ID: %s\n", FLOW_TITLE_ID);
    printf("  Built with ps3recomp\n");
    printf("================================================\n\n");
}

/* ---------------------------------------------------------------------------
 * Main
 * -----------------------------------------------------------------------*/

int main(int argc, char* argv[])
{
    print_banner();

    /* Game data directory (override via CLI) */
    const char* game_dir = FLOW_GAME_DIR;
    if (argc > 1)
        game_dir = argv[1];

    printf("[init] Game directory: %s\n", game_dir);

    /* 1. Initialize memory subsystem -- allocates the guest address space. */
    printf("[init] Memory subsystem...\n");
    if (!ps3::memory::init(FLOW_MAIN_MEM_SIZE)) {
        fprintf(stderr, "ERROR: Failed to initialize memory subsystem\n");
        return 1;
    }

    /* 2. Initialize thread manager. */
    printf("[init] Thread subsystem...\n");
    if (!ps3::thread::init(FLOW_MAX_PPU_THREADS)) {
        fprintf(stderr, "ERROR: Failed to initialize thread subsystem\n");
        ps3::memory::shutdown();
        return 1;
    }

    /* 3. Initialize HLE module tables (cellSysmodule, cellFs, etc.). */
    printf("[init] HLE modules...\n");
    if (!ps3::modules::init()) {
        fprintf(stderr, "ERROR: Failed to initialize module subsystem\n");
        ps3::thread::shutdown();
        ps3::memory::shutdown();
        return 1;
    }
    ps3::modules::register_builtin_modules();

    /* 4. Set up filesystem path mapping. */
    snprintf(g_sys_fs_root, sizeof(g_sys_fs_root), "%s", game_dir);
    printf("[init] Filesystem root: %s\n", g_sys_fs_root);

    /* 5. Load ELF data segments into virtual memory. */
    char elf_path[512];
    snprintf(elf_path, sizeof(elf_path), "%s/EBOOT.elf", game_dir);
    if (!elf_load_segments(elf_path)) {
        printf("[init] Warning: Could not load ELF segments from %s\n", elf_path);
        printf("[init] Recompiled code may crash if it accesses global data\n");
    }

    /* 6. Load recompiled function table. */
    printf("[init] Loaded %zu recompiled functions\n", g_recompiled_func_count);

    /* 7. Create the main PPU thread and enter the game's main(). */
    printf("[init] Creating main PPU thread (stack %u KB)...\n",
           FLOW_STACK_SIZE / 1024);

    auto main_entry = [](uint64_t arg) {
        (void)arg;
        recomp_game_main(nullptr);
    };

    uint64_t main_tid = ps3::thread::create_main_thread(
        main_entry, 0, FLOW_STACK_SIZE, "flow_main");

    printf("[init] Main thread ID: %llu -- entering game at 0x%X\n\n",
           (unsigned long long)main_tid, FLOW_ENTRY_POINT);

    /* 8. Wait for the main thread to finish. */
    ps3::thread::join_thread(main_tid);

    /* 9. Cleanup. */
    printf("\n[exit] flOw has exited. Shutting down...\n");
    ps3::modules::shutdown();
    ps3::thread::shutdown();
    ps3::memory::shutdown();

    return 0;
}
